/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.agileninjas.dementiasmartwatch;

public final class R {
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int metaButtonBarButtonStyle=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int metaButtonBarStyle=0x7f010000;
    }
    public static final class color {
        public static final int black_overlay=0x7f040000;
    }
    public static final class drawable {
        public static final int contact=0x7f020000;
        public static final int ic_launcher=0x7f020001;
        public static final int panic_button=0x7f020002;
        public static final int panic_button_old=0x7f020003;
    }
    public static final class id {
        public static final int analog_clock=0x7f070001;
        public static final int digital_clock=0x7f070002;
        public static final int fullscreen_content=0x7f070000;
        public static final int fullscreen_content_controls=0x7f070003;
        public static final int fullscreen_content_controls2=0x7f070004;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        /**  Battery 
 Battery 
         */
        public static final int battery_low=0x7f05000f;
        /**  Panic Button 
 Panic Button 
         */
        public static final int dummy_button=0x7f050001;
        public static final int dummy_content=0x7f050018;
        public static final int email_app_start_content=0x7f050006;
        public static final int email_app_start_subject=0x7f050005;
        public static final int email_app_stop_content=0x7f050008;
        public static final int email_app_stop_subject=0x7f050007;
        public static final int email_battery_content=0x7f05000e;
        public static final int email_battery_subject=0x7f05000d;
        public static final int email_gps_in_boundry_content=0x7f05000c;
        public static final int email_gps_in_boundry_subject=0x7f05000b;
        public static final int email_gps_out_of_boundry_content=0x7f05000a;
        public static final int email_gps_out_of_boundry_subject=0x7f050009;
        public static final int email_panic_content=0x7f050004;
        /**  Email 
 Email 
         */
        public static final int email_panic_subject=0x7f050003;
        public static final int emergency_contact_number=0x7f050014;
        /**  GPS 
 GPS 
         */
        public static final int gps_no_provider=0x7f050010;
        public static final int gps_out_of_boundry=0x7f050011;
        public static final int imageContact=0x7f050017;
        public static final int imagePanicButton=0x7f050016;
        /**  Others 
 Others 
         */
        public static final int ok=0x7f050015;
        public static final int panic_button_send=0x7f050002;
        /**  Display Contact on panic 
 Display Contact on panic 
         */
        public static final int patient_name=0x7f050012;
        public static final int relative_name=0x7f050013;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.

    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.

        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.

    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060001;
        public static final int ButtonBar=0x7f060003;
        public static final int ButtonBarButton=0x7f060004;
        public static final int FullscreenActionBarStyle=0x7f060005;
        public static final int FullscreenTheme=0x7f060002;
    }
    public static final class styleable {
        /** 
         Declare custom theme attributes that allow changing which styles are
         used for button bars depending on the API level.
         ?android:attr/buttonBarStyle is new as of API 11 so this is
         necessary to support previous API levels.
    
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ButtonBarContainerTheme_metaButtonBarButtonStyle com.agileninjas.dementiasmartwatch:metaButtonBarButtonStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #ButtonBarContainerTheme_metaButtonBarStyle com.agileninjas.dementiasmartwatch:metaButtonBarStyle}</code></td><td></td></tr>
           </table>
           @see #ButtonBarContainerTheme_metaButtonBarButtonStyle
           @see #ButtonBarContainerTheme_metaButtonBarStyle
         */
        public static final int[] ButtonBarContainerTheme = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link com.agileninjas.dementiasmartwatch.R.attr#metaButtonBarButtonStyle}
          attribute's value can be found in the {@link #ButtonBarContainerTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.agileninjas.dementiasmartwatch:metaButtonBarButtonStyle
        */
        public static final int ButtonBarContainerTheme_metaButtonBarButtonStyle = 1;
        /**
          <p>This symbol is the offset where the {@link com.agileninjas.dementiasmartwatch.R.attr#metaButtonBarStyle}
          attribute's value can be found in the {@link #ButtonBarContainerTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.agileninjas.dementiasmartwatch:metaButtonBarStyle
        */
        public static final int ButtonBarContainerTheme_metaButtonBarStyle = 0;
    };
}
